name: untitled1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.6.2"

dependencies:
  flutter:
    sdk: flutter

  # UI / Utility
  fl_chart: ^0.70.2
  google_fonts: ^4.0.4
  table_calendar: ^3.2.0
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  path_provider: ^2.1.2
  intl: ^0.20.2

  # 사진 촬영 & HTTP
  image_picker: ^1.1.2
  http: ^0.13.3
  http_parser: ^4.0.0
  mime: ^1.0.4

  # URL 열기 및 메타데이터 파싱, 이미지 캐시
  url_launcher: ^6.3.1
  metadata_fetch: ^0.4.1
  cached_network_image: ^3.2.3
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

